DEFAULT_TAG_VALUE = 'None'
TITLE_TAG_NAME = 'TIT2'
ARTIST_TAG_NAME = 'TPE1'
ALBUM_NAME_TAG_NAME = 'TALB'
ALBUM_COVER_TAG_NAME = 'APIC:'
PRESERVED_TAGS = [TITLE_TAG_NAME, ARTIST_TAG_NAME, ALBUM_NAME_TAG_NAME, ALBUM_COVER_TAG_NAME]
