DISCOGS_URL = 'https://api.discogs.com/database/search'

DEFAULT_TAG_VALUE = 'None'
TITLE_TAG_NAME = 'TIT2'
ARTIST_TAG_NAME = 'TPE1'
ALBUM_NAME_TAG_NAME = 'TALB'
TRACK_NUMBER_TAG_NAME = 'TRCK'
TRACK_YEAR_TAG_NAME = 'TDRC'
ALBUM_COVER_TAG_NAME = 'APIC:'
PRESERVED_TAGS = [TITLE_TAG_NAME, ARTIST_TAG_NAME, ALBUM_NAME_TAG_NAME, ALBUM_COVER_TAG_NAME, TRACK_NUMBER_TAG_NAME,
                  TRACK_YEAR_TAG_NAME]

SPOTIFY_API_URL = 'https://api.spotify.com/v1/search'
SPOTIFY_TOKEN_URL = 'https://accounts.spotify.com/api/token'
